### ISSUE TITLE
BigDecimal divideAndRemainder bad result

### ISSUE THREAD

**Issue by skolson** [ionspin/kotlin-multiplatform-bignum#112]
Given this code:
```
val x = BigDecimal.fromShort(Short.MIN_VALUE)
val result = x.divideAndRemainder(BigDecimal.ONE)
```
x is displayed in debugger with correct value -3.2768E+4. Result.first should be the same, and result.second should be zero. Instead, this is displayed in debugger:
    result.first = -3.2769E+4
    result.second = 1.0

So far this is the only case I've hit in early unit testing, so am unsure what other ways the underlying bug may manifest. It's possible this happens whenever signs of numerator and divisor differ. 

Environment:
kotlin 1.4.0-rc
com.ionspin.kotlin:bignum:0.1.6-1.4.0-rc-SNAPSHOT
running junit5 unit test using Kotest 4.2.0 invoking multiplatform common functions using BigDecimal

**Comment by skolson** [comment]
More info, indicating wider bug. Given this code running in the same environment
`
    val limit = BigDecimal.fromInt(Int.MAX_VALUE)
    val lowLimit = BigDecimal.fromInt(Int.MIN_VALUE)
`
limit gets correct value of 2.147483647E+9 or 2147483647
lowLimit however gets incorrect value -1.8446744071562067968E+18
lowLimit should be -2.147483648E+9
have not tried to debug into code to see why yet

**Comment by ionspin** [comment]
Thanks for reporting! I'll give it a look today.

**Comment by skolson** [comment]
The BigDecimal.fromInt(Int.MIN_VALUE) is weird. The debugger displays the element in **magnitude** of the **BigInteger** it is constructing with the correct value of -2147483648, and **sign** is correct, but the debugger value displayed for the BigInteger itself is -18446744071562067968. I'm not sure why, but sure enough when it gets to function **numberOfDecimalDigits()** in BigInteger, that returns 19 when it should be 10. I'm still looking around :-)

**Comment by skolson** [comment]
The debugger is dynamically calling toString, and it comes back wrong due to trouble in divrem again. In the Biginteger toString method when it does **copy divrem baseArray** the answer comes back with the huge result 18446744071562067968. I'll stop looking here unless I can do something useful to help you, let me know if I can. I'm a motivated new user, with time :-)
Easy to recreate:
```val badness = BigDecimal.fromInt(Int.MIN_VALUE).toString()```

**Comment by ionspin** [comment]
Hey @skolson, I just got off work so I can take a look at this. 

But first, your effort is greatly appreciated, I don't have a lot of time and such debugging insight can be a great help when solving issues. 

I'll first look into the divrem problem that you saw, as that might be the most serious.

The number you saw (18446744071562067968) looked very familiar, at first I thought it was ULong.MAX_VALUE, but I was wrong, it turns out it's ULong.MAX_VALUE - Int.MAX_VALUE

**Comment by ionspin** [comment]
Ok, this is a fun issue, the actual problem stems from `BigInteger.fromInt(intValue)`, because the BigInteger class is actually backing implementation of the BigDecimal. So when I tried to get a BigInteger.fromInt(Int.MIN_VALUE) I also got that weird ULong.MAX_VALUE - Int.MAX_VALUE

So let's look at what `BigInteger.fromInt(intValue)` does:
```
override fun fromInt(int: Int) = BigInteger(int)
```
it calls a constructor for BigInt that takes just an integer, which is this:
```
constructor(int: Int) : this(arithmetic.fromInt(int), determinSignFromNumber(int))
```
The next step is going into actual arithmetic implementation `arithmetic.fromInt(int)` which is this:
```
override fun fromInt(int: Int): ULongArray = ulongArrayOf(int.absoluteValue.toULong())
```
This one needs a bit of explaining. The ULong array is there because all BigIntegers are represented as an array of **63** bit numbers and a separate sign variable. To make sure that the number is always positive we use `absoluteValue`.

So in our case where we try `BigInteger.fromInt(Int.MIN_VALUE)` we would expect a BigInt that has a long array of [2147483648] and a Sign.NEGATIVE, but we got a [18446744071562067968] a Sign.NEGATIVE. It looks like the `absolutValue` didn't work in our case, but that is a kotlin call!

And the solution comes from the actual `absoluteValue` documentation, which states:
```
/**
 * Returns the absolute value of this value.
 *
 * Special cases:
 *   - `Int.MIN_VALUE.absoluteValue` is `Int.MIN_VALUE` due to an overflow
 *
 * @see abs function
```
Which is exactly our situation, so instead of returning what we expected to be 2147483648, we got -2147483648 (note the sign), then converted that to ULong (unsigned long), which became 18446744071562067968, and continued to break everything else, because that number has a 1 set at bit 64, which shouldn't be possible in the 63 arithmetic implementation that BigInteger currently uses.

That shouldn't happen to Short though, so I still need to look into that divrem with Short.MIN_VALUE and 1.

**Comment by ionspin** [comment]
The second part of the problem, wrong divrem, was a bit more convoluted, as it was in the rounding function, code which I have trouble remembering the most. The problem there was that the function tried to apply rounding even if the digit that was being discarded is 0, so in this case a negative number and default rounding, which is `FLOOR` caused the Short.MIN_VALUE (which internally when dividing in this case becomes -32768.0 and then needs to be rounded back) was decreased by one to -32769, instead of just returning -32768

**Comment by skolson** [comment]
Awesome, thanks for finding this so quickly. Is there already a 0.2.0 snapshot built with 1.4.0-rc that I could try? If not, lemme know and I can look into building the current master tomorrow myself and see how it acts.

**Comment by ionspin** [comment]
Hey @skolson, sorry for the late reply, just got off work again, each merge to master is automatically built and published to sonatype snapshot repository, it's not 0.2.0 yet, but you can find the current build here:
```
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }
}
implementation("com.ionspin.kotlin:bignum:0.1.6-1.4.0-rc-SNAPSHOT")
```

**Comment by skolson** [comment]
I just tested with this and this fix looks good. Unfortunately it hits a comparison error with two negatives :-) Since this is closed, I'll open a new issue.
