### ISSUE TITLE
BigDecimal divide not working properly

### ISSUE THREAD

**Issue by olivergasa** [ionspin/kotlin-multiplatform-bignum#127]
At first, thank you very much for your work! I really appreciate it.
But there is one thing :)

**Describe the bug**
BigDecimal divide function not always returning the correct result.
In short, if I divide 2.2 by 2 it should result in 1.1 but it results in 1.1E-1 which is 0.11.

**To Reproduce**
bigDecimal = BigDecimal.parseString("2.2").divide(BigDecimal.parseString("2"))

**Expected behavior**
bigDecimal == BigDecimal.parseString("1.1") // should be true

**Platform**
Running tests in JVM

**Additional context**
If I divide 22 by 2 it should result in 11 but it results in 1.1. 
Same kind of error for 222 / 2. Result is 11.1.
POSITIVE CASE: If I divide e.g. 123.456 by 2 it results in 61.728.

Bug occurred in version 0.2.0

**Comment by ionspin** [comment]
Hi Oliver,

Thank you very much for reporting this issue! It's caused by a recent change of adding scale parameter to BigDecimal numbers and an unfortunate mistake of not setting a correct exponent on static `BigDecimal.TEN` which caused a test that should have failed for scale actually finish successfully.

It's still rather embarrassing that none of the tests caught that division with infinite precision is not working correctly.

I'll fix this and push a new version out today or tomorrow, as this is one of the main functionalities

**Comment by olivergasa** [comment]
Hi Ugljesa,

thank you for your quick reply and the fix. I wrote a test which covers all the operations I mentioned in my first post. 
Unfortunately the positive case, which was 123.456 / 2 now results in 617.28. 

`
var bigDecimal = BigDecimal.fromFloat(123.456f).divide(BigDecimal.fromFloat(2.0f))
assertEquals(BigDecimal.fromFloat(61.728f), bigDecimal)
`

The other tests passed.

**Comment by ionspin** [comment]
You are right, that's not correct, I must have missed something, I'll take a look at it and hopefully fix it by tomorrow. Thanks for reporting it!

**Comment by ionspin** [comment]
Hi Oliver,

Hopefully I fixed the issue now, the fix is in 0.2.2, which should be available from maven in next couple of hours, or 0.2.3-SNAPSHOT which should be available in half an hour or so. Please share if you still face issues.

One note though regarding the division with unlimited/infinite precision which you are using here, it's going to throw an error if you result is not terminating after a certain number of digits, you can read more about that here https://github.com/ionspin/kotlin-multiplatform-bignum#infinite-precision
Usually you should be defining decimal mode, which defines what is the precision you want, and how to round up/down once that precision is reached. You can read more about it here https://github.com/ionspin/kotlin-multiplatform-bignum#decimalmode

**Comment by olivergasa** [comment]
Hi Ugljesa,

I tested it in the morning and according to my tests its now all green. Tests were successful.
Thanks the links. As I was just adding the basic operations I don't know yet how I will use the division operation but its good to keep that in mind.

Thank you! You're doing a great job 👍
