### ISSUE TITLE
Attempting to perform an infinite precision BigDecimal exponentiation

### ISSUE THREAD

**Issue by JoonasC** [ionspin/kotlin-multiplatform-bignum#200]
The readme mentions that division is the only operation which cannot be performed with infinite precision, but the exponentiation feature uses division internally, which therefore makes exponentiation susceptible to the same problems as division.

Is this a documentation issue or a bug?

**Comment by ionspin** [comment]
Hi @JoonasC, good catch, this is a documentation issue, it should be mentioned that exponentiation with negative exponents has the same limitation as division. The reason for the limitation is that results of some divisions can be infinitely long, i.e. 1/3 = 0.333333... and the library needs to have way to stop instead of calculating to infinity (or more realistically until it runs out of memory)

**Comment by JoonasC** [comment]
Could you also implement an exponentation method which accepts a decimal mode?

**Comment by ionspin** [comment]
Sure, I'll look into that as well!
