### ISSUE TITLE
Add non-module based serialization

### ISSUE THREAD

**Issue by sergeych** [ionspin/kotlin-multiplatform-bignum#217]
using serialization via module is a pain. Could you provide "default" serialization for your classes so we can use it without rewriting so much code? We're professional developers and in our projects there are MANY places where we do de/serialization, and update each place to incorporate your modules is a pain...

**Comment by ionspin** [comment]
Hi Sergey,

I'm very glad to hear that you are using this library in a professional environment!

Adding kotlinx-serialization to the core bignum library will not happen because not everyone needs serialization and I don't wont to add bloat to the core library.

If you have ideas on how to improve or add default serialization using bignum-serialization-kotlinx modules pull requests are very welcome!

With that said, since I will not be changing the core library module to add serialization I'll close this issue.
