### ISSUE TITLE
ArithmeticException Thrown when Converting BigDecimal with Decimal to doubleValue or floatValue

### ISSUE THREAD

**Issue by apoupardsmartb** [ionspin/kotlin-multiplatform-bignum#262]
**Describe the bug**
An ArithmeticException ("java.lang.ArithmeticException: Value cannot be narrowed to float") is thrown when attempting to convert a BigDecimal with a decimal value to either a doubleValue or floatValue.

**To Reproduce**
These are the steps to reproduce this behavior:

1. Use the following test operations:
    ```
    @Test
    fun arithmeticExceptionDouble() {
        val value = 2.001.toBigDecimal().doubleValue()
        Assertions.assertThat(value).isEqualTo(2.001)
    }
    @Test
    fun arithmeticExceptionFloat() {
        val value = BigDecimal.fromFloat(0.001f).floatValue()
        Assertions.assertThat(value).isEqualTo(0.001f)
    }
    ```
    I was able to reproduce it in your main branch:
    https://github.com/apoupardsmartb/kotlin-multiplatform-bignum/pull/1/files
    
2. Run these test cases on a JVM platform.

**Expected behavior**
The expectation is for the BigDecimal with decimal value to be successfully converted to either a doubleValue or floatValue without throwing an exception. In the test cases, the converted value should match the original decimal value (2.001 for doubleValue and 0.001f for floatValue).

**Platform**
 - JVM

**Additional context**
This issue arose while attempting to convert BigDecimal with decimal values to either a doubleValue or floatValue. The specific exception that is thrown is: java.lang.ArithmeticException: Value cannot be narrowed to float.

**Comment by ionspin** [comment]
Hi @apoupardsmartb , thank you for taking the time to look into this, but this is the expected behavior, because of limitations of IEEE 754 standard, value 2.001 can not be precisely represented and the library prevents you from accidentally introducing conversion error by throwing an exception.

If you are fine with conversion error when converting to double or float, then you can pass a parameter `exactRequired = false` to doubleValue or floatValue. But you should be aware that the value that JVM represents as float 2.001 is actually stored as 2.000999927520751953125.

A fun way to experience this is to run the following code:

```
    @Test
    fun ieee754() {
        val aFloat : Float = 2.001f
        val bFloat : Float = 2.000999927520751953125f

        val aDouble : Double= 2.001
        val bDouble : Double= 2.00099999999999988986587595718
        assertEquals(aFloat, bFloat)
        assertEquals(aDouble, bDouble)
    }
```

And note that this test will pass.

You can explore more here: https://www.h-schmidt.net/FloatConverter/IEEE754.html
