### ISSUE TITLE
[BigDecimal] High memory usage

### ISSUE THREAD

**Issue by avently** [ionspin/kotlin-multiplatform-bignum#28]
**Is your feature request related to a problem?**
Your implementation uses too much internal variables. This makes RAM usage higher than everyone wants. Think about million of instances on mobile devices (my app creates tens thousands of instances per second and heap memory is high even with Java's implementation).

**Describe the solution you'd like**
Maybe a good idea would be to replace BigInteger with Long or Int where it is acceptable.  Also maybe you can find a way to remove some variables at all (it's possible).

**Additional context**
Didn't tested your BigDecimal implementation but saw a code. It has non implemented methods so I'll wait before it will be ready and will compare the RAM usage with Java's version of BigDecimal. 
P.s. thanks for making it possible. I wrote my own implementation of it just because there were no alternatives. It's more lightweight than Java's version but soooo slow.

**Comment by ionspin** [comment]
Yes, neither BigDecimal or BigInteger are optimized either for speed or memory usage. I plan to release 0.1.0 soon™, which should be functionally complete. Then for version 0.2.0 goal is to work on optimizing both speed by implementing more efficient algorithms for different sizes, and memory usage. I'll keep this issue open to track overall progress on that BigDecimal memory usage. Thanks for suggestions.

**Comment by ionspin** [comment]
Version 0.1.2 is taking initial steps towards solving this by handling empty words that are results of arithmetic operations differently. Still a lot of work to be done before the space useage is optimal.

**Comment by ionspin** [comment]
There have been several improvements regarding amount of allocations in BigInteger arithmetic since January (BigDecimal is practially just a wrapper around BigInteger with more operations) , mostly made by more precise allocations when executing arithmetic operations, as well as passing information on zero words without the need to allocate new arrays. 

Since this issue is too broad, all future improvements will be tracked in more specific issues, such as a future improvement of in place addition and multiplication operations that will be used by base case multiplication. 

Once pull request #108 is merged this issue will be closed.

**Comment by avently** [comment]
Good, thank you, @ionspin
