### ISSUE TITLE
Include dependency per platform?

### ISSUE THREAD

**Issue by RdeWilde** [ionspin/kotlin-multiplatform-bignum#54]
Do I have to explicit define this library for every platform? The readme says just this: `implementation("com.ionspin.kotlin:bignum:0.1.0")`, but should I add the variants with suffix (-jvm, -js etc) to the various sourceSets? Or only in a main dependency?

**Comment by ionspin** [comment]
You should have the following line
`enableFeaturePreview("GRADLE_METADATA")`
set up in your settings.gradle. That enables Gradle to resolve the proper artifacts per platform. If you are missing that line then you should add the them individually like mentioned in #51. Then you do increase the risk of having version mismatch between common and platform artifacts. 

I'll add that to the readme to make it more clear.

**Comment by ionspin** [comment]
I just found out that since Gradle 5.3 it's automatically using Metadata, but version 1.0 not 0.4 that I am currently publishing, so when I bump the gradle version, it won't be usable on Gradle < 5.3, I need to figure out if that affects Android in any way. For now you can use Gradle < 5.3 and `enableFeaturePreview`
